# Generated by Django 4.2 on 2023-04-14 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pantry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='Title',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='item',
            name='Category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Pantry.category'),
        ),
    ]
