# Generated by Django 4.2 on 2023-04-18 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pantry', '0002_alter_category_title_alter_item_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['Category', 'Title']},
        ),
    ]
