# Generated by Django 4.2 on 2023-04-22 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pantry', '0003_alter_item_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['Title']},
        ),
    ]
